# Generated by Django 5.0.6 on 2024-05-19 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 19, 30, 20, 420727, tzinfo=datetime.timezone.utc)),
        ),
    ]
