# Generated by Django 5.0.6 on 2024-05-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentEntry', '0004_alter_student_birthdate_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_address',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_initial',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('lastname', 'firstname')},
        ),
    ]
