# Generated by Django 5.0.6 on 2024-05-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentEntry', '0006_alter_course_course_name_alter_student_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_initial',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
